### ISSUE TITLE
Tactic_Data_Dir on virtual machine TSI

### ISSUE THREAD

**Issue by quaam** [listyque/TACTIC-Handler#2]
I'm on windows 10 using the fedora vmware image for the server. Problem is that the TACTIC_DATA_DIR is on the image at \\home\tactic\tactic_data\ so I cant set it as an environment variable in windows. 

Is there a workaround for VMware image users?

thanks

**Comment by listyque** [comment]
Create environment variable "TACTIC_DATA_DIR" and add as a value path where you hold the sources of TACTIC_Handler, for example: "D:\CGProjects\tacticbase\TACTIC_handler"
It's just pointing to the folder where all the sources lie (original TACTIC base dir doesn't needed), you can even hardcode it to your permanent path.
for ex. DATA_DIR = 'D:/CGProjects/tacticbase/TACTIC-handler'

**Comment by tws0002** [comment]
Sorry im quite new in coding!! so hope you can help me.
is this compatible with TACTIC Team 4.4?
I still can't connect with it!! sorry
do i need to change something in here to make it work ?

class Env(object):
    def __init__(self):
        self.project = None
        self.namespace = None
        self.user = None
        self.password = None
        self.server = None
        self.ticket = None
        self.data_dir = None
        self.install_dir = None
        self.asset_dir = None
        self.temp_dir = None
        self.types_list = None
        self.defaults = {
            'project': 'cgshort',
            'namespace': 'cgshort',
            'user': 'listy',
            'pass': 'makesome',
            'server': '127.0.0.1:9123',
            'ticket': None,
            'data_dir': str('C:/Program Files (x86)/TACTIC 4.4/TACTIC_handler').replace('\\', '/'),
            'install_dir': str('C:/Program Files (x86)/TACTIC 4.4/TACTIC_handler' + '/src/client').replace('\\', '/'),
            'asset_dir': str('C:/ProgramData/Tactic/data/assets').replace('\\', '/'),
            'temp_dir': tempfile.gettempdir(),
            'types_list': ['maya', 'houdini', '3dsmax', 'nuke', ''],
        }

        self.settings = QtCore.QSettings('TACTIC Handler', 'TACTIC Handling Tool')

**Comment by listyque** [comment]
YES!
You must change at least this strings:
'project': 'cgshort',  - to your default project
'namespace': 'cgshort', - namespace of your project
'user': 'listy', - admin, for ex.
'pass': 'makesome', - admin
'server': '127.0.0.1:9123', - your tactic team, or VM.
'data_dir': str('C:/Program Files (x86)/TACTIC 4.4/TACTIC_handler').replace('\', '/'), - may be better place Handler to better place, say d:/tchandler: 'data_dir': str('d:/tchandler/TACTIC_handler').replace('\\', '/')

And don't forget, to have PySide in your python

**Comment by quaam** [comment]
I got further along and made the appropriate changes mentioned above. But when I run it in maya a window pops up saying "Looks like TACTIC server isn't running. Start Server?" 

No matter what option I select this shows up:

'exceptions.KeyError' object has no attribute 'errno'
# Error: KeyError: file C:\Program Files\Autodesk\Maya2016\bin\python27.zip\os.py line 423: TACTIC_INSTALL_DIR # 

If I run it from the command prompt, I get this error:

'exceptions.KeyError' object has no attribute 'errno'
Traceback (most recent call last):
  File "y:\tactic\TACTIC_handler\main_standalone.pyw", line 88, in <module>
    startup()
  File "y:\tactic\TACTIC_handler\main_standalone.pyw", line 77, in startup
    if tc.ping_srv():
  File "y:\tactic\TACTIC_handler\lib\tactic_classes.py", line 136, in ping_srv
    server_restart(True)
  File "y:\tactic\TACTIC_handler\lib\tactic_classes.py", line 103, in server_restart
    run_bat()
  File "y:\tactic\TACTIC_handler\lib\tactic_classes.py", line 80, in run_bat
    path = os.path.normpath(os.environ['TACTIC_INSTALL_DIR'] + os.sep + os.pardir)
  File "C:\Python27\lib\os.py", line 425, in __getitem__
    return self.data[key.upper()]
KeyError: 'TACTIC_INSTALL_DIR'

Once again my server is running from the fedora image on win 10. Thanks

**Comment by listyque** [comment]
Just make emty variable TACTIC_INSTALL_DIR =)
Also make TACTIC_ASSET_DIR variable
Where do You store your assets when using VM image?

**Comment by tws0002** [comment]
Not sure how to start server!! Pls Help!!

 RESTART: C:\Program Files (x86)\TACTIC 4.4\TACTIC_Handler\main_standalone.pyw 
server_start error
(AttributeError("'Fault' object has no attribute 'errno'",), 'ping_srv')
Starting TACTIC Server...
Hold on for 3 seconds until server start...

Traceback (most recent call last):
  File "C:\Program Files (x86)\TACTIC 4.4\TACTIC_Handler\main_standalone.pyw", line 93, in <module>
    startup()
  File "C:\Program Files (x86)\TACTIC 4.4\TACTIC_Handler\main_standalone.pyw", line 79, in startup
    if tc.ping_srv():
  File "C:\Program Files (x86)\TACTIC 4.4\TACTIC_Handler\lib\tactic_classes.py", line 152, in ping_srv
    server_restart(True)
  File "C:\Program Files (x86)\TACTIC 4.4\TACTIC_Handler\lib\tactic_classes.py", line 120, in server_restart
    run_bat()
  File "C:\Program Files (x86)\TACTIC 4.4\TACTIC_Handler\lib\tactic_classes.py", line 102, in run_bat
    server = get_server()
  File "C:\Program Files (x86)\TACTIC 4.4\TACTIC_Handler\lib\tactic_classes.py", line 72, in get_server
    new_ticket,
  File "C:\Program Files (x86)\TACTIC 4.4\TACTIC_Handler\lib\tactic_classes.py", line 51, in server_auth
    ticket = tactic_srv.get_ticket(log, psw)
  File "C:\Program Files (x86)\TACTIC 4.4\TACTIC_Handler\lib\client\tactic_client_lib\tactic_server_stub.py", line 555, in get_ticket
    return my.server.get_ticket(login, password, site)
  File "C:\Python27\lib\xmlrpclib.py", line 1240, in __call__
    return self.__send(self.__name, args)
  File "C:\Python27\lib\xmlrpclib.py", line 1599, in __request
    verbose=self.__verbose
  File "C:\Python27\lib\xmlrpclib.py", line 1280, in request
    return self.single_request(host, handler, request_body, verbose)
  File "C:\Python27\lib\xmlrpclib.py", line 1313, in single_request
    return self.parse_response(response)
  File "C:\Python27\lib\xmlrpclib.py", line 1490, in parse_response
    return u.close()
  File "C:\Python27\lib\xmlrpclib.py", line 799, in close
    raise Fault(**self._stack[0])
Fault: <Fault 1: 'Login/Password combination incorrect'>

**Comment by listyque** [comment]
Did you started your Tactic TEAM server?
Use TACTIC Server.bat from tactic install directory

**Comment by quaam** [comment]
my assets dir is set to Z:\assets. I've actually gone back to Tactic Team because the vmware was giving me too many issues.

In Tactic Team I am having the same issues addressed before. Even though my tactic server is started and I am able to log in from a browser to Tactic client, I'm getting the error saying that the server is not running when I try to run the script from maya or the standalone one.

Not sure what the issue is.

**Comment by listyque** [comment]
I will record some video explaining how to setup everything to work properly, and share with you.

**Comment by tws0002** [comment]
it will be great. Thank you listyque

**Comment by quaam** [comment]
that would be great! thanks. I've tried tactic team and tactic vmware and both have been unsuccessful

**Comment by tws0002** [comment]
Hi listyque when can we see the demo video ? Thanks

**Comment by listyque** [comment]
https://github.com/listyque/TACTIC-Handler/wiki/Setup-Instrcutions-(updated)

**Comment by tws0002** [comment]
Thank you listyque.
