### ISSUE TITLE
Context and process in asset name

### ISSUE THREAD

**Issue by Sugrobski** [listyque/TACTIC-Handler#28]
For today asset's name consist of name itself then process name and context after that (optionaly). Could you please replace this order so the process name will be the last part of whole asset's name? See the picture. 
![2017-04-29_160403](https://cloud.githubusercontent.com/assets/28104403/25555749/3a1de092-2cf7-11e7-97a9-383be5924aca.png)

**Comment by listyque** [comment]
This is fixed in free cg template in naming.
