### ISSUE TITLE
UI codes and logics codes are mixing together

### ISSUE THREAD

**Issue by eslym** [listyque/TACTIC-Handler#34]
This make the whole system harder to understand and its very hard for people to make modifications, I hope this can be improved.

p/s: people will be happier if they can see more info in readme file, for example I have to go through code to know this application is integrate with TACTIC through xmlrpc

**Comment by listyque** [comment]
Can you provide some example, and how I can improve it?

**Comment by listyque** [comment]
I am planning to update reamde, as soon as stable ready to work version released. There will be screenshots, last how to start instructions and some videos.
About MVC. I think it is not necesssary for PySide/Pyqt projects. I made UI logic separated, so any new UI can be added separately. TACTIC objects, and other classes separated too,
If you can link me to good project made using MVC it will be great

**Comment by 0nepeop1e** [comment]
great, as long as the code does not mix, so if anyone wants to improve UI wont conflict with logic codes, same for logic as well

**Comment by listyque** [comment]
Here is zero interface example, where you can use my (not perfect) api, to get from TACTIC db what ever you want, and make your own GUI.

import lib.tactic_classes as tc
from lib.environment import env_server, env_inst

# above code needed to generate ticket
# kwargs = dict(
#         host='127.0.0.1:9123',
#         project='sthpw',
#         login='admin',
#         password='admin',
#         site='',
#         get_ticket=True
#     )
# tc.server_auth(**kwargs)  #can be used once, then when ticket generated reuse it

# print(env_server.get_ticket()) # printing ticket

env_server.set_server('127.0.0.1:9123')
env_server.set_ticket('f61408fdffa51dcd56a3a82ae25d0d29')  # pasted ticket here

projects_dict = tc.get_all_projects()  # getting all projects from TACTIC db
env_inst.projects = projects_dict
print(projects_dict)

the_pirate_project = projects_dict['the_pirate']

project_stypes = the_pirate_project.get_stypes()

props_stype = project_stypes['cgshort/props']

print(props_stype)
props_stype_pipeline = props_stype.get_pipeline()['cgshort/props']

processes = props_stype_pipeline.process.keys()  # all stype pipeline processes

assets = tc.assets_query_new(
                query=('*', 0),
                stype='cgshort/props',
                project='the_pirate'
            )

sobjects = tc.get_sobjects([], assets, project_code=the_pirate_project.get_code())

print(sobjects)
snapshots = []
for sobj in sobjects.values():
    print(sobj.info)  # print SObject info
    snapshots.append(sobj.get_snapshots())  # getting snapshots for this sobject, see SObject class
    # also can be queryed notes, tasks etc...

# with Snapshot class you can get files, previews, notes for file and etc...
for snapshot in snapshots:
    print(snapshot.get_files_objects())

**Comment by 0nepeop1e** [comment]
thanks, this help a lot

**Comment by listyque** [comment]
All server queryes and commands now can be found in Debug log interface.
For exmaple:
[05.01.2019 - 00:12:23] [ INF ] thenv.env_inst.get_check_tree("game", "checkin_out", "game/asset").add_new_sobject() ----- //1988 : Module: ui_checkin_out_classes.py, Function: add_new_sobject()
[05.01.2019 - 00:12:36] [ LOG ] Making Commit Insert for Asset ----- //0199 : Module: tactic_widgets.py, Function: commit()
[05.01.2019 - 00:12:36] [ INF ] thenv.get_tc().server_start(project="game").insert("game/asset", {u'name': u'Bottle'}) ----- //0202 : Module: tactic_widgets.py, Function: commit()
