### ISSUE TITLE
Batch update file info

### ISSUE THREAD

**Issue by EuniceChen1** [listyque/TACTIC-Handler#37]
Is there a way to batch update file paths if the file directory were to be changed? or if not, add an enhancement for this kind of function. Currently, once I check in a file, I can only change the source path when I right click, edit-info.  So this is not practical if for example, I have 30 versions, then I have to change the source path 30 times.

**Comment by listyque** [comment]
Yeah, batch edit is planned. There will be mass delete, delete with context. Mass edit will be added too. It is not too hard to implement.
This will be implemented as Database Table Editor. So there will be ability to edit any cell in the table.

**Comment by listyque** [comment]
Here is the example of mass renaming.
This is for sthpw/file table, but can be used for any table. What you need is activate Tactic Admin, throug Project tab in Configuration > right click "Toggle project".
![mass_rename_example](https://github.com/listyque/TACTIC-Handler/blob/stable/screenshots/examples/mass_file_rename_example.png?raw=true)

You can select multiple items and edit them in ColumnsEditor.
To access ColumnsEditor > right click on any dock (snapshot browser for example), and select Columns Editor.
