### ISSUE TITLE
Setup instructions for Tactic Enterprise on a linux machine and windows machine as client

### ISSUE THREAD

**Issue by quaam** [listyque/TACTIC-Handler#38]
Currently the instructions are towards a Tactic Team setup. 

My current setup is latest tactic enteprise version (4.6) on Fedora 28 server and tactic handler (stable) on windows 10 pro. I've been able to set it up so that maya handler opens and works, but I haven't been able to get the standalone to work. 

i have TACTIC_DATA_DIR and TACTIC_INSTALL_DIR windows environment variables pointing to network paths to the linux server. 

I had to manually update Qt.py to version 1.1.0 (replacing just Qt.py in lib/side) because it was causing some errors with loadui. updating it fixed the issues, but this issue still remains:

Traceback (most recent call last):
  File "P:\TACTIC_Handler\main_standalone.py", line 6, in <module>
    from lib.side.Qt import QtWidgets as QtGui
ImportError: cannot import name QtWidgets

I'm hoping updated setup instructions with this type of set up might shed some light in what I have done wrong. 

Thank you.

**Comment by listyque** [comment]
Hi. Do you have pyside or qt packages installed in your python environment?

**Comment by quaam** [comment]
thanks for the reply. C:\Python27 and C:\Python27\scripts are on my environment path. I tried adding P:\TACTIC_HANDLER\lib\side to see if it helped


![python-site-packages](https://user-images.githubusercontent.com/19613523/45334892-d0cb6c80-b54a-11e8-8127-f4ce83cad2e8.PNG)

I also tried with a batch file that sets PYTHONPATH to P:\TACTIC_HANDLER\lib\side and then runs main_standalone.py to see if that made a difference.

I also ran python -v main_standalone.py and it seems to go through paths from what I can tell. I included the output.
[verbose.txt](https://github.com/listyque/TACTIC-Handler/files/2369151/verbose.txt)

**Comment by listyque** [comment]
Can you try to write simple QDialog app and run it with your python + Qt.py?

**Comment by EuniceChen1** [comment]
Try to with PySide 2 as well while you're at it
