### ISSUE TITLE
Modo3d support? 

### ISSUE THREAD

**Issue by fire** [listyque/TACTIC-Handler#4]
Where would I start?

**Comment by listyque** [comment]
Hi. Currently i am working on some time-consuming things, that helps me not to rewrite internal TACTIC api, cause when i rewrite their api, i must update it when they roll every new version.
So, when i done it, i will update the code here, and you can take it, and then add support for Modo if you want. Only thing to do is integrate PySide interface to Modo, and add functions to save/open/import etc...

**Comment by listyque** [comment]
At this time, You can try to run Tactic + Tactic Handler. Test it to work properly, and see if you can integrate it to Modo
