### ISSUE TITLE
Blender Support?

### ISSUE THREAD

**Issue by fire** [listyque/TACTIC-Handler#40]
Hi, 

Trying to understand how I can Integrate blender with TACTIC-Handler?

**Comment by listyque** [comment]
I have started to create version which works through ports.
Standalone version with UI will be started and living in the tray, and blender scripts will call checkins.
If You have any thoughts welcome to share them!

**Comment by listyque** [comment]
You can notice tactic_api_client.py, which can be executed. This is started but not done yet api client.
Blender is not using Qt UI, native integration isn't possible

**Comment by listyque** [comment]
Initial support will be added in next few releases. Along with the maya commandPort support for standalone (more safe and crash-proof)
