### ISSUE TITLE
How to install?

### ISSUE THREAD

**Issue by orangemn6** [listyque/TACTIC-Handler#41]
How do you install this? the guide does not work

**Comment by listyque** [comment]
Hi!
The guides is on the way.
I will notify when it is done.

They will be here: http://tactic-handler.tk/docs/requirements/

**Comment by orangemn6** [comment]
ok thx maybe you should write wip next to the docs link

**Comment by listyque** [comment]
For anyone who wants "just try":
I made a portable version of TACTIC + TH

TEST VERSION

How to use: Unpack and run TACTIC-Server.bat

Then you can access TACTIC via web browser from localhost:9123

[tactic_team48.zip](http://tacitc-handler.online/docs/tactic_team48.zip)

I also added silent version which is lies in system tray: TACTIC-Server_Silent.bat


And Tactic-Handler: TACTIC-Handler.bat

Tactic Handler should be executed after TACTIC server is fully started and accessible
