### ISSUE TITLE
need help (explanation) for checkin repository type and method type

### ISSUE THREAD

**Issue by lalamax3d** [listyque/TACTIC-Handler#7]
Hi, could you please explain about Repository types and Method types
i can see, General and Local, what exactly is the difference.?
in case of Method, i can get a feel of approaches, but a bit confused about preallocate / upload etc?

![handlerquestions_01](https://cloud.githubusercontent.com/assets/567387/22308579/5e1584a0-e369-11e6-895f-85149b71e6a8.jpg)

**Comment by listyque** [comment]
Repositories it is your folders, or servers. General - main folder, where you can store all files, Local - repo on you pc, for example. You can rename this, map to any folder, etc.
Basically this is different paths to file system or network, with colored representation (snapshots changing their color with color of repo).
When you for example, renamed your server from, for ex., "server-3d" to "server-3d-new", you can remap this path in config, and continue checkin and checkout snapshots.

Checkin Method is not-so finished, and at this moment permanently working in in-place mode, but slightly different from default TACTIC in-place. It he future all TACTIC methods will be supported, Upload, copy, move and etc.
