### ISSUE TITLE
Hi listyque are you still updating Tactic handler for nuke and houdini?

### ISSUE THREAD

**Issue by tws0002** [listyque/TACTIC-Handler#9]
Hi listyque,

are you still updating Tactic handler for nuke and houdini?

Thanks 
Desmond

**Comment by listyque** [comment]
I will be updating this app in the near and far future.
I've been busy last months finishing our first 3d movie, so it is released, and i have more time to some coding stuff.

**Comment by tws0002** [comment]
will wait for it. 

would you mind to share what movie you are completed?

Thanks 
Desmond

**Comment by listyque** [comment]
https://www.youtube.com/watch?v=OsD54oJSeIA
This is russian movie

**Comment by tws0002** [comment]
nice work. 
so do the studio using tactic-handler as a studio pipeline?
do u mind to share the working experiences on this project?

Thanks
Desmond

**Comment by listyque** [comment]
No. Studio has it's own task-tracking and file managing tools, separated frowm each other. Some tools to handle rendered sequences have been made by me.
Tactic handler have more features already in file-managing.
